spring.application.name=AICareerCopilot

# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

# Ollama
spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text

spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=llama3.2:latest
spring.ai.ollama.chat.num-thread=4
spring.ai.ollama.chat.num-predict=220
spring.ai.ollama.chat.temperature=0.1

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# RAG
app.rag.similarity-threshold=0.30